//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PictionaryMusicalCliente.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SALIR DE LA PARTIDA.
        /// </summary>
        public static string ajustesPartidaTextoSalirPartida {
            get {
                return ResourceManager.GetString("ajustesPartidaTextoSalirPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CERRAR SESIÓN.
        /// </summary>
        public static string ajustesPrincipalTextoCerrarSesion {
            get {
                return ResourceManager.GetString("ajustesPrincipalTextoCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso.
        /// </summary>
        public static string alertaAviso {
            get {
                return ResourceManager.GetString("alertaAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENVIAR SOLICITUD.
        /// </summary>
        public static string buscarAmigoTextoEnviaSolicitud {
            get {
                return ResourceManager.GetString("buscarAmigoTextoEnviaSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el usuario:.
        /// </summary>
        public static string buscarAmigoTextoIngreseUsuario {
            get {
                return ResourceManager.GetString("buscarAmigoTextoIngreseUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el código de verificación enviado a su correo:.
        /// </summary>
        public static string cambiarContraseñaTextoCodigoVerificacion {
            get {
                return ResourceManager.GetString("cambiarContraseñaTextoCodigoVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme su contraseña.
        /// </summary>
        public static string cambiarContraseñaTextoConfirmeContraseña {
            get {
                return ResourceManager.GetString("cambiarContraseñaTextoConfirmeContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la nueva contraseña: .
        /// </summary>
        public static string cambiarContraseñaTextoIngresaNuevaContraseña {
            get {
                return ResourceManager.GetString("cambiarContraseñaTextoIngresaNuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REENVIAR CÓDIGO.
        /// </summary>
        public static string cambiarContraseñaTextoReenviarCodigo {
            get {
                return ResourceManager.GetString("cambiarContraseñaTextoReenviarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VERIFICAR.
        /// </summary>
        public static string cambiarContraseñaTextoVerificar {
            get {
                return ResourceManager.GetString("cambiarContraseñaTextoVerificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de querer cerrar la sesión?.
        /// </summary>
        public static string cerrarSesionTextoConfirmacion {
            get {
                return ResourceManager.GetString("cerrarSesionTextoConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de puntos.
        /// </summary>
        public static string clasificacionTextoTotalPuntos {
            get {
                return ResourceManager.GetString("clasificacionTextoTotalPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de rondas ganadas.
        /// </summary>
        public static string clasificacionTextoTotalRondas {
            get {
                return ResourceManager.GetString("clasificacionTextoTotalRondas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1. Dibuja sin usar palabras..
        /// </summary>
        public static string comoJugarTextoInstrucciones {
            get {
                return ResourceManager.GetString("comoJugarTextoInstrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complete los datos solicitados:.
        /// </summary>
        public static string crearCuentaTextoDatosSolicitados {
            get {
                return ResourceManager.GetString("crearCuentaTextoDatosSolicitados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Cuenta creada exitosamente!.
        /// </summary>
        public static string crearCuentaTextoExitosoMensaje {
            get {
                return ResourceManager.GetString("crearCuentaTextoExitosoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro completo.
        /// </summary>
        public static string crearCuentaTextoExitosoTitulo {
            get {
                return ResourceManager.GetString("crearCuentaTextoExitosoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de querer eliminar de su lista de amigos a .
        /// </summary>
        public static string eliminarAmigoTextoConfirmacion {
            get {
                return ResourceManager.GetString("eliminarAmigoTextoConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIMINAR AMIGO.
        /// </summary>
        public static string eliminarAmigoTextoEliminar {
            get {
                return ResourceManager.GetString("eliminarAmigoTextoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al guardar los datos:.
        /// </summary>
        public static string errorTextoBaseDeDatosMensaje {
            get {
                return ResourceManager.GetString("errorTextoBaseDeDatosMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de base de datos.
        /// </summary>
        public static string errorTextoBaseDeDatosTitulo {
            get {
                return ResourceManager.GetString("errorTextoBaseDeDatosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico en uso.
        /// </summary>
        public static string errorTextoCorreoEnUso {
            get {
                return ResourceManager.GetString("errorTextoCorreoEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es necesario ingresar el correo para su recuperación.
        /// </summary>
        public static string errorTextoCorreoRecuperacion {
            get {
                return ResourceManager.GetString("errorTextoCorreoRecuperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo iniciar sesión.
        /// </summary>
        public static string errorTextoCredencialesTitulo {
            get {
                return ResourceManager.GetString("errorTextoCredencialesTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe una cuenta con esas credenciales.
        /// </summary>
        public static string errorTextoCuentaRelacionada {
            get {
                return ResourceManager.GetString("errorTextoCuentaRelacionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró la partida.
        /// </summary>
        public static string errorTextoNoEncuentraPartida {
            get {
                return ResourceManager.GetString("errorTextoNoEncuentraPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario en uso.
        /// </summary>
        public static string errorTextoUsuarioEnUso {
            get {
                return ResourceManager.GetString("errorTextoUsuarioEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de querer expulsar a ?.
        /// </summary>
        public static string expulsarTextoConfirmacion {
            get {
                return ResourceManager.GetString("expulsarTextoConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXPULSAR.
        /// </summary>
        public static string expulsarTextoExpulsar {
            get {
                return ResourceManager.GetString("expulsarTextoExpulsar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXPULSAR JUGADOR.
        /// </summary>
        public static string expulsarTextoExpulsarJugador {
            get {
                return ResourceManager.GetString("expulsarTextoExpulsarJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añade la razón de la expulsión….
        /// </summary>
        public static string expulsarTextoRazonExpulsion {
            get {
                return ResourceManager.GetString("expulsarTextoRazonExpulsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACEPTAR.
        /// </summary>
        public static string globalTextoAceptar {
            get {
                return ResourceManager.GetString("globalTextoAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AJUSTES.
        /// </summary>
        public static string globalTextoAjustes {
            get {
                return ResourceManager.GetString("globalTextoAjustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string globalTextoApellido {
            get {
                return ResourceManager.GetString("globalTextoApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BUSCAR UN AMIGO.
        /// </summary>
        public static string globalTextoBuscarAmigo {
            get {
                return ResourceManager.GetString("globalTextoBuscarAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELAR.
        /// </summary>
        public static string globalTextoCancelar {
            get {
                return ResourceManager.GetString("globalTextoCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLASIFICACIÓN.
        /// </summary>
        public static string globalTextoClasificacion {
            get {
                return ResourceManager.GetString("globalTextoClasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿CÓMO JUGAR?.
        /// </summary>
        public static string globalTextoComoJugar {
            get {
                return ResourceManager.GetString("globalTextoComoJugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONFIRMAR.
        /// </summary>
        public static string globalTextoConfirmar {
            get {
                return ResourceManager.GetString("globalTextoConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string globalTextoContraseña {
            get {
                return ResourceManager.GetString("globalTextoContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string globalTextoCorreo {
            get {
                return ResourceManager.GetString("globalTextoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREAR CUENTA.
        /// </summary>
        public static string globalTextoCrearCuenta {
            get {
                return ResourceManager.GetString("globalTextoCrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efectos de sonido.
        /// </summary>
        public static string globalTextoEfectosSonido {
            get {
                return ResourceManager.GetString("globalTextoEfectosSonido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIMINAR.
        /// </summary>
        public static string globalTextoEliminar {
            get {
                return ResourceManager.GetString("globalTextoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener mínimo 8 caracteres y máximo 15, así como contener mínimo una mayúscula, un número y un carácter especial.
        /// </summary>
        public static string globalTextoEspecificaContraseña {
            get {
                return ResourceManager.GetString("globalTextoEspecificaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el código de la partida:.
        /// </summary>
        public static string globalTextoIngreseCodigoPartida {
            get {
                return ResourceManager.GetString("globalTextoIngreseCodigoPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INVITACIONES.
        /// </summary>
        public static string globalTextoInvitaciones {
            get {
                return ResourceManager.GetString("globalTextoInvitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INVITAR.
        /// </summary>
        public static string globalTextoInvitar {
            get {
                return ResourceManager.GetString("globalTextoInvitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string globalTextoNombre {
            get {
                return ResourceManager.GetString("globalTextoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REGRESAR.
        /// </summary>
        public static string globalTextoRegresar {
            get {
                return ResourceManager.GetString("globalTextoRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar un avatar.
        /// </summary>
        public static string globalTextoSeleccionarAvatar {
            get {
                return ResourceManager.GetString("globalTextoSeleccionarAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOLICITUDES.
        /// </summary>
        public static string globalTextoSolicitudes {
            get {
                return ResourceManager.GetString("globalTextoSolicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡UNIRSE!.
        /// </summary>
        public static string globalTextoUnirse {
            get {
                return ResourceManager.GetString("globalTextoUnirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UNIRSE A UNA SALA.
        /// </summary>
        public static string globalTextoUnirseASala {
            get {
                return ResourceManager.GetString("globalTextoUnirseASala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string globalTextoUsuario {
            get {
                return ResourceManager.GetString("globalTextoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen de las canciones.
        /// </summary>
        public static string globalTextoVolumenCanciones {
            get {
                return ResourceManager.GetString("globalTextoVolumenCanciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string idiomaTextoEspañol {
            get {
                return ResourceManager.GetString("idiomaTextoEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string idiomaTextoIdioma {
            get {
                return ResourceManager.GetString("idiomaTextoIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string idiomaTextoIngles {
            get {
                return ResourceManager.GetString("idiomaTextoIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico / Usuario.
        /// </summary>
        public static string inicioSesionTextoCorreoUsuario {
            get {
                return ResourceManager.GetString("inicioSesionTextoCorreoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENTRAR.
        /// </summary>
        public static string inicioSesionTextoEntrar {
            get {
                return ResourceManager.GetString("inicioSesionTextoEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENTRAR COMO INVITADO.
        /// </summary>
        public static string inicioSesionTextoEntrarInvitado {
            get {
                return ResourceManager.GetString("inicioSesionTextoEntrarInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string inicioSesionTextoOlvidasteContraseña {
            get {
                return ResourceManager.GetString("inicioSesionTextoOlvidasteContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  te invitó a unirse a su partida!.
        /// </summary>
        public static string invitacionTextoInvitado {
            get {
                return ResourceManager.GetString("invitacionTextoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INVITADO.
        /// </summary>
        public static string invitarAmigosTextoInvitado {
            get {
                return ResourceManager.GetString("invitarAmigosTextoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INVITAR AMIGOS.
        /// </summary>
        public static string invitarAmigosTextoInvitarAmigos {
            get {
                return ResourceManager.GetString("invitarAmigosTextoInvitarAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡INICIAR PARTIDA!.
        /// </summary>
        public static string partidaAdminTextoIniciarPartida {
            get {
                return ResourceManager.GetString("partidaAdminTextoIniciarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INVITAR AL CORREO.
        /// </summary>
        public static string partidaAdminTextoInvitarCorreo {
            get {
                return ResourceManager.GetString("partidaAdminTextoInvitarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string partidaTextoChat {
            get {
                return ResourceManager.GetString("partidaTextoChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código:.
        /// </summary>
        public static string partidaTextoCodigo {
            get {
                return ResourceManager.GetString("partidaTextoCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida en curso.
        /// </summary>
        public static string partidaTextoPartidaEnCurso {
            get {
                return ResourceManager.GetString("partidaTextoPartidaEnCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ronda:.
        /// </summary>
        public static string partidaTextoRonda {
            get {
                return ResourceManager.GetString("partidaTextoRonda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CAMBIAR CONTRASEÑA.
        /// </summary>
        public static string perfilTextoCambiarContraseña {
            get {
                return ResourceManager.GetString("perfilTextoCambiarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR CAMBIOS.
        /// </summary>
        public static string perfilTextoGuardarCambios {
            get {
                return ResourceManager.GetString("perfilTextoGuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MI PERFIL.
        /// </summary>
        public static string perfilTextoMiPerfil {
            get {
                return ResourceManager.GetString("perfilTextoMiPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega alguna red social:.
        /// </summary>
        public static string perfilTextoRedesSociales {
            get {
                return ResourceManager.GetString("perfilTextoRedesSociales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AMIGOS.
        /// </summary>
        public static string principalTextoAmigos {
            get {
                return ResourceManager.GetString("principalTextoAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREAR UNA SALA.
        /// </summary>
        public static string principalTextoCrearSala {
            get {
                return ResourceManager.GetString("principalTextoCrearSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Difícil.
        /// </summary>
        public static string principalTextoDificil {
            get {
                return ResourceManager.GetString("principalTextoDificil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificultad:.
        /// </summary>
        public static string principalTextoDificultad {
            get {
                return ResourceManager.GetString("principalTextoDificultad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fácil.
        /// </summary>
        public static string principalTextoFacil {
            get {
                return ResourceManager.GetString("principalTextoFacil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma de las canciones.
        /// </summary>
        public static string principalTextoIdiomaCanciones {
            get {
                return ResourceManager.GetString("principalTextoIdiomaCanciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡JUGAR!.
        /// </summary>
        public static string principalTextoJugar {
            get {
                return ResourceManager.GetString("principalTextoJugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Media.
        /// </summary>
        public static string principalTextoMedia {
            get {
                return ResourceManager.GetString("principalTextoMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mixto.
        /// </summary>
        public static string principalTextoMixto {
            get {
                return ResourceManager.GetString("principalTextoMixto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de rondas:.
        /// </summary>
        public static string principalTextoNumeroRondas {
            get {
                return ResourceManager.GetString("principalTextoNumeroRondas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de la ronda (segundos).
        /// </summary>
        public static string principalTextoTiempoRonda {
            get {
                return ResourceManager.GetString("principalTextoTiempoRonda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventana Principal.
        /// </summary>
        public static string principalTextoTitulo {
            get {
                return ResourceManager.GetString("principalTextoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de querer salir de la partida?.
        /// </summary>
        public static string salirPartidaTextoConfirmación {
            get {
                return ResourceManager.GetString("salirPartidaTextoConfirmación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en-MX.
        /// </summary>
        public static string TagEspañol {
            get {
                return ResourceManager.GetString("TagEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en-US.
        /// </summary>
        public static string TagIngles {
            get {
                return ResourceManager.GetString("TagIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Sesión.
        /// </summary>
        public static string tituloTextoInicioSesion {
            get {
                return ResourceManager.GetString("tituloTextoInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MUSICAL.
        /// </summary>
        public static string tituloTextoMusical {
            get {
                return ResourceManager.GetString("tituloTextoMusical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PICTIONARY.
        /// </summary>
        public static string tituloTextoPictionary {
            get {
                return ResourceManager.GetString("tituloTextoPictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cuenta.
        /// </summary>
        public static string tituloTextoRegistroUsuarios {
            get {
                return ResourceManager.GetString("tituloTextoRegistroUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala.
        /// </summary>
        public static string tituloTextoVentanaPrincipal {
            get {
                return ResourceManager.GetString("tituloTextoVentanaPrincipal", resourceCulture);
            }
        }
    }
}
