//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Práctica_WPF_con_Entity_Framework.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Práctica_WPF_con_Entity_Framework.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complete los datos solicitados:.
        /// </summary>
        public static string crearCuentaTextoDatosSolicitados {
            get {
                return ResourceManager.GetString("crearCuentaTextoDatosSolicitados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Cuenta creada exitosamente!.
        /// </summary>
        public static string crearCuentaTextoExitosoMensaje {
            get {
                return ResourceManager.GetString("crearCuentaTextoExitosoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro completo.
        /// </summary>
        public static string crearCuentaTextoExitosoTitulo {
            get {
                return ResourceManager.GetString("crearCuentaTextoExitosoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al guardar los datos:.
        /// </summary>
        public static string errorTextoBaseDeDatosMensaje {
            get {
                return ResourceManager.GetString("errorTextoBaseDeDatosMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de base de datos.
        /// </summary>
        public static string errorTextoBaseDeDatosTitulo {
            get {
                return ResourceManager.GetString("errorTextoBaseDeDatosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico en uso.
        /// </summary>
        public static string errorTextoCorreoEnUso {
            get {
                return ResourceManager.GetString("errorTextoCorreoEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es necesario ingresar el correo para su recuperación.
        /// </summary>
        public static string errorTextoCorreoRecuperacion {
            get {
                return ResourceManager.GetString("errorTextoCorreoRecuperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo iniciar sesión.
        /// </summary>
        public static string errorTextoCredencialesTitulo {
            get {
                return ResourceManager.GetString("errorTextoCredencialesTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe una cuenta con esas credenciales.
        /// </summary>
        public static string errorTextoCuentaRelacionada {
            get {
                return ResourceManager.GetString("errorTextoCuentaRelacionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario en uso.
        /// </summary>
        public static string errorTextoUsuarioEnUso {
            get {
                return ResourceManager.GetString("errorTextoUsuarioEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string globalTextoApellido {
            get {
                return ResourceManager.GetString("globalTextoApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELAR.
        /// </summary>
        public static string globalTextoCancelar {
            get {
                return ResourceManager.GetString("globalTextoCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string globalTextoContraseña {
            get {
                return ResourceManager.GetString("globalTextoContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string globalTextoCorreo {
            get {
                return ResourceManager.GetString("globalTextoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREAR CUENTA.
        /// </summary>
        public static string globalTextoCrearCuenta {
            get {
                return ResourceManager.GetString("globalTextoCrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener mínimo 8 caracteres y máximo 15, así como contener mínimo una mayúscula, un número y un carácter especial.
        /// </summary>
        public static string globalTextoEspecificaContraseña {
            get {
                return ResourceManager.GetString("globalTextoEspecificaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string globalTextoNombre {
            get {
                return ResourceManager.GetString("globalTextoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar un avatar.
        /// </summary>
        public static string globalTextoSeleccionarAvatar {
            get {
                return ResourceManager.GetString("globalTextoSeleccionarAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string globalTextoUsuario {
            get {
                return ResourceManager.GetString("globalTextoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string idiomaTextoEspañol {
            get {
                return ResourceManager.GetString("idiomaTextoEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string idiomaTextoIdioma {
            get {
                return ResourceManager.GetString("idiomaTextoIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string idiomaTextoIngles {
            get {
                return ResourceManager.GetString("idiomaTextoIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico / Usuario.
        /// </summary>
        public static string inicioSesionTextoCorreoUsuario {
            get {
                return ResourceManager.GetString("inicioSesionTextoCorreoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENTRAR.
        /// </summary>
        public static string inicioSesionTextoEntrar {
            get {
                return ResourceManager.GetString("inicioSesionTextoEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENTRAR COMO INVITADO.
        /// </summary>
        public static string inicioSesionTextoEntrarInvitado {
            get {
                return ResourceManager.GetString("inicioSesionTextoEntrarInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string inicioSesionTextoOlvidasteContraseña {
            get {
                return ResourceManager.GetString("inicioSesionTextoOlvidasteContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en-MX.
        /// </summary>
        public static string TagEspañol {
            get {
                return ResourceManager.GetString("TagEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en-US.
        /// </summary>
        public static string TagIngles {
            get {
                return ResourceManager.GetString("TagIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Sesión.
        /// </summary>
        public static string tituloTextoInicioSesion {
            get {
                return ResourceManager.GetString("tituloTextoInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MUSICAL.
        /// </summary>
        public static string tituloTextoMusical {
            get {
                return ResourceManager.GetString("tituloTextoMusical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PICTIONARY.
        /// </summary>
        public static string tituloTextoPictionary {
            get {
                return ResourceManager.GetString("tituloTextoPictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cuenta.
        /// </summary>
        public static string tituloTextoRegistroUsuarios {
            get {
                return ResourceManager.GetString("tituloTextoRegistroUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala.
        /// </summary>
        public static string tituloTextoVentanaPrincipal {
            get {
                return ResourceManager.GetString("tituloTextoVentanaPrincipal", resourceCulture);
            }
        }
    }
}
