//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PictionaryMusicalCliente.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SALIR DE LA PARTIDA.
        /// </summary>
        public static string ajustesPartidaTextoSalirPartida {
            get {
                return ResourceManager.GetString("ajustesPartidaTextoSalirPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CERRAR SESIÓN.
        /// </summary>
        public static string ajustesPrincipalTextoCerrarSesion {
            get {
                return ResourceManager.GetString("ajustesPrincipalTextoCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADVERTENCIA.
        /// </summary>
        public static string alertaTextoAviso {
            get {
                return ResourceManager.GetString("alertaTextoAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código que enviamos para confirmar el cambio de contraseña..
        /// </summary>
        public static string avisoTextoCodigoDescripcionCambio {
            get {
                return ResourceManager.GetString("avisoTextoCodigoDescripcionCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de verificación enviado a {0}..
        /// </summary>
        public static string avisoTextoCodigoDescripcionCorreo {
            get {
                return ResourceManager.GetString("avisoTextoCodigoDescripcionCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de verificación que enviamos a tu correo..
        /// </summary>
        public static string avisoTextoCodigoDescripcionGenerica {
            get {
                return ResourceManager.GetString("avisoTextoCodigoDescripcionGenerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código que enviamos para restablecer tu contraseña..
        /// </summary>
        public static string avisoTextoCodigoDescripcionRecuperacion {
            get {
                return ResourceManager.GetString("avisoTextoCodigoDescripcionRecuperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se envió un código de verificación a tu correo electrónico..
        /// </summary>
        public static string avisoTextoCodigoEnviado {
            get {
                return ResourceManager.GetString("avisoTextoCodigoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se envió un nuevo código a su correo electrónico..
        /// </summary>
        public static string avisoTextoCodigoReenviado {
            get {
                return ResourceManager.GetString("avisoTextoCodigoReenviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código verificado correctamente. Continúe con el cambio de contraseña..
        /// </summary>
        public static string avisoTextoCodigoVerificadoCambio {
            get {
                return ResourceManager.GetString("avisoTextoCodigoVerificadoCambio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código verificado correctamente..
        /// </summary>
        public static string avisoTextoCodigoVerificadoCorrecto {
            get {
                return ResourceManager.GetString("avisoTextoCodigoVerificadoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un problema de comunicación con el servidor. Se mostrarán los datos actuales de la sesión..
        /// </summary>
        public static string avisoTextoComunicacionServidorSesion {
            get {
                return ResourceManager.GetString("avisoTextoComunicacionServidorSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña se actualizó correctamente..
        /// </summary>
        public static string avisoTextoContrasenaActualizada {
            get {
                return ResourceManager.GetString("avisoTextoContrasenaActualizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a la red social.
        /// </summary>
        public static string avisoTextoNombreRedSocialGenerica {
            get {
                return ResourceManager.GetString("avisoTextoNombreRedSocialGenerica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos del perfil se actualizaron correctamente..
        /// </summary>
        public static string avisoTextoPerfilActualizado {
            get {
                return ResourceManager.GetString("avisoTextoPerfilActualizado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Hay datos inválidos o campos vacíos, por favor verifique sus datos..
        /// </summary>
        public static string errorTextoCamposInvalidosGenerico {
            get {
                return ResourceManager.GetString("errorTextoCamposInvalidosGenerico", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No es posible reenviar el código todavía..
        /// </summary>
        public static string avisoTextoReenvioCodigoNoDisponible {
            get {
                return ResourceManager.GetString("avisoTextoReenvioCodigoNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro completado exitosamente..
        /// </summary>
        public static string avisoTextoRegistroCompletado {
            get {
                return ResourceManager.GetString("avisoTextoRegistroCompletado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo contactar al servidor. Se mostrarán los datos actuales de la sesión..
        /// </summary>
        public static string avisoTextoServidorSesionDatos {
            get {
                return ResourceManager.GetString("avisoTextoServidorSesionDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor tardó demasiado en responder. Se mostrarán los datos actuales de la sesión..
        /// </summary>
        public static string avisoTextoServidorTiempoSesion {
            get {
                return ResourceManager.GetString("avisoTextoServidorTiempoSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENVIAR SOLICITUD.
        /// </summary>
        public static string buscarAmigoTextoEnviaSolicitud {
            get {
                return ResourceManager.GetString("buscarAmigoTextoEnviaSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el usuario:.
        /// </summary>
        public static string buscarAmigoTextoIngreseUsuario {
            get {
                return ResourceManager.GetString("buscarAmigoTextoIngreseUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el código de verificación enviado a su correo:.
        /// </summary>
        public static string cambiarContraseñaTextoCodigoVerificacion {
            get {
                return ResourceManager.GetString("cambiarContraseñaTextoCodigoVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme su contraseña.
        /// </summary>
        public static string cambiarContraseñaTextoConfirmeContraseña {
            get {
                return ResourceManager.GetString("cambiarContraseñaTextoConfirmeContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la nueva contraseña: .
        /// </summary>
        public static string cambiarContraseñaTextoIngresaNuevaContraseña {
            get {
                return ResourceManager.GetString("cambiarContraseñaTextoIngresaNuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REENVIAR CÓDIGO.
        /// </summary>
        public static string cambiarContraseñaTextoReenviarCodigo {
            get {
                return ResourceManager.GetString("cambiarContraseñaTextoReenviarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VERIFICAR.
        /// </summary>
        public static string cambiarContraseñaTextoVerificar {
            get {
                return ResourceManager.GetString("cambiarContraseñaTextoVerificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de querer cerrar la sesión?.
        /// </summary>
        public static string cerrarSesionTextoConfirmacion {
            get {
                return ResourceManager.GetString("cerrarSesionTextoConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar por puntos.
        /// </summary>
        public static string clasificacionTextoOrdenarPuntos {
            get {
                return ResourceManager.GetString("clasificacionTextoOrdenarPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar por rondas.
        /// </summary>
        public static string clasificacionTextoOrdenarRondas {
            get {
                return ResourceManager.GetString("clasificacionTextoOrdenarRondas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de puntos.
        /// </summary>
        public static string clasificacionTextoTotalPuntos {
            get {
                return ResourceManager.GetString("clasificacionTextoTotalPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de rondas ganadas.
        /// </summary>
        public static string clasificacionTextoTotalRondas {
            get {
                return ResourceManager.GetString("clasificacionTextoTotalRondas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1. Dibuja sin usar palabras..
        /// </summary>
        public static string comoJugarTextoInstrucciones {
            get {
                return ResourceManager.GetString("comoJugarTextoInstrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complete los datos solicitados:.
        /// </summary>
        public static string crearCuentaTextoDatosSolicitados {
            get {
                return ResourceManager.GetString("crearCuentaTextoDatosSolicitados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Cuenta creada exitosamente!.
        /// </summary>
        public static string crearCuentaTextoExitosoMensaje {
            get {
                return ResourceManager.GetString("crearCuentaTextoExitosoMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro completo.
        /// </summary>
        public static string crearCuentaTextoExitosoTitulo {
            get {
                return ResourceManager.GetString("crearCuentaTextoExitosoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de querer eliminar de su lista de amigos a .
        /// </summary>
        public static string eliminarAmigoTextoConfirmacion {
            get {
                return ResourceManager.GetString("eliminarAmigoTextoConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIMINAR AMIGO.
        /// </summary>
        public static string eliminarAmigoTextoEliminar {
            get {
                return ResourceManager.GetString("eliminarAmigoTextoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo actualizar la contraseña. Intente nuevamente..
        /// </summary>
        public static string errorTextoActualizarContrasena {
            get {
                return ResourceManager.GetString("errorTextoActualizarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo actualizar el perfil. Intente nuevamente..
        /// </summary>
        public static string errorTextoActualizarPerfil {
            get {
                return ResourceManager.GetString("errorTextoActualizarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el apellido del jugador..
        /// </summary>
        public static string errorTextoApellidoJugadorRequerido {
            get {
                return ResourceManager.GetString("errorTextoApellidoJugadorRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido es obligatorio y no debe exceder 50 caracteres..
        /// </summary>
        public static string errorTextoApellidoObligatorioLongitud {
            get {
                return ResourceManager.GetString("errorTextoApellidoObligatorioLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El avatar seleccionado no existe..
        /// </summary>
        public static string errorTextoAvatarNoExiste {
            get {
                return ResourceManager.GetString("errorTextoAvatarNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al guardar los datos:.
        /// </summary>
        public static string errorTextoBaseDeDatosMensaje {
            get {
                return ResourceManager.GetString("errorTextoBaseDeDatosMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de base de datos.
        /// </summary>
        public static string errorTextoBaseDeDatosTitulo {
            get {
                return ResourceManager.GetString("errorTextoBaseDeDatosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El {0} no debe superar {1} caracteres..
        /// </summary>
        public static string errorTextoCampoLongitudMaxima {
            get {
                return ResourceManager.GetString("errorTextoCampoLongitudMaxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el {0}..
        /// </summary>
        public static string errorTextoCampoRequerido {
            get {
                return ResourceManager.GetString("errorTextoCampoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de verificación ha expirado. Solicite uno nuevo..
        /// </summary>
        public static string errorTextoCodigoExpiradoSolicitarNuevo {
            get {
                return ResourceManager.GetString("errorTextoCodigoExpiradoSolicitarNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código ingresado no es correcto o ha expirado..
        /// </summary>
        public static string errorTextoCodigoIncorrectoExpirado {
            get {
                return ResourceManager.GetString("errorTextoCodigoIncorrectoExpirado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el código de verificación enviado a su correo..
        /// </summary>
        public static string errorTextoCodigoVerificacionRequerido {
            get {
                return ResourceManager.GetString("errorTextoCodigoVerificacionRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un problema de comunicación al consultar los avatares..
        /// </summary>
        public static string errorTextoComunicacionConsultarAvatares {
            get {
                return ResourceManager.GetString("errorTextoComunicacionConsultarAvatares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un problema de comunicación al obtener los avatares del servidor..
        /// </summary>
        public static string errorTextoComunicacionObtenerAvatares {
            get {
                return ResourceManager.GetString("errorTextoComunicacionObtenerAvatares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un problema de comunicación con el servidor. Intente más tarde..
        /// </summary>
        public static string errorTextoComunicacionServidorMasTarde {
            get {
                return ResourceManager.GetString("errorTextoComunicacionServidorMasTarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un problema de comunicación con el servidor. Intente nuevamente..
        /// </summary>
        public static string errorTextoComunicacionServidorNuevamente {
            get {
                return ResourceManager.GetString("errorTextoComunicacionServidorNuevamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un problema de comunicación con el servidor..
        /// </summary>
        public static string errorTextoComunicacionServidorSimple {
            get {
                return ResourceManager.GetString("errorTextoComunicacionServidorSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese y confirme la nueva contraseña..
        /// </summary>
        public static string errorTextoConfirmacionContrasenaRequerida {
            get {
                return ResourceManager.GetString("errorTextoConfirmacionContrasenaRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener de 8 a 15 caracteres con al menos una mayúscula, un número y un carácter especial..
        /// </summary>
        public static string errorTextoContrasenaFormato {
            get {
                return ResourceManager.GetString("errorTextoContrasenaFormato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese una contraseña..
        /// </summary>
        public static string errorTextoContrasenaRequerida {
            get {
                return ResourceManager.GetString("errorTextoContrasenaRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden..
        /// </summary>
        public static string errorTextoContrasenasNoCoinciden {
            get {
                return ResourceManager.GetString("errorTextoContrasenasNoCoinciden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico en uso.
        /// </summary>
        public static string errorTextoCorreoEnUso {
            get {
                return ResourceManager.GetString("errorTextoCorreoEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un correo electrónico válido..
        /// </summary>
        public static string errorTextoCorreoInvalido {
            get {
                return ResourceManager.GetString("errorTextoCorreoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es necesario ingresar el correo para su recuperación.
        /// </summary>
        public static string errorTextoCorreoRecuperacion {
            get {
                return ResourceManager.GetString("errorTextoCorreoRecuperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un correo electrónico..
        /// </summary>
        public static string errorTextoCorreoRequerido {
            get {
                return ResourceManager.GetString("errorTextoCorreoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo o usuario ya está registrado..
        /// </summary>
        public static string errorTextoCorreoUsuarioRegistrado {
            get {
                return ResourceManager.GetString("errorTextoCorreoUsuarioRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo y el usuario ya están registrados..
        /// </summary>
        public static string errorTextoCorreoUsuarioRegistrados {
            get {
                return ResourceManager.GetString("errorTextoCorreoUsuarioRegistrados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el usuario o correo y la contraseña..
        /// </summary>
        public static string errorTextoCredencialesIncompletas {
            get {
                return ResourceManager.GetString("errorTextoCredencialesIncompletas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales incorrectas..
        /// </summary>
        public static string errorTextoCredencialesIncorrectas {
            get {
                return ResourceManager.GetString("errorTextoCredencialesIncorrectas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo iniciar sesión.
        /// </summary>
        public static string errorTextoCredencialesTitulo {
            get {
                return ResourceManager.GetString("errorTextoCredencialesTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos de la cuenta no están disponibles..
        /// </summary>
        public static string errorTextoCuentaDatosNoDisponibles {
            get {
                return ResourceManager.GetString("errorTextoCuentaDatosNoDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró la cuenta asociada a la sesión actual..
        /// </summary>
        public static string errorTextoCuentaNoEncontradaSesion {
            get {
                return ResourceManager.GetString("errorTextoCuentaNoEncontradaSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró una cuenta con el usuario o correo proporcionado..
        /// </summary>
        public static string errorTextoCuentaNoRegistrada {
            get {
                return ResourceManager.GetString("errorTextoCuentaNoRegistrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe una cuenta con esas credenciales.
        /// </summary>
        public static string errorTextoCuentaRelacionada {
            get {
                return ResourceManager.GetString("errorTextoCuentaRelacionada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo determinar el usuario actual para cambiar la contraseña..
        /// </summary>
        public static string errorTextoDeterminarUsuarioCambioContrasena {
            get {
                return ResourceManager.GetString("errorTextoDeterminarUsuarioCambioContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo enviar el código de verificación. Verifique la información e intente de nuevo..
        /// </summary>
        public static string errorTextoEnvioCodigoVerificacionDatos {
            get {
                return ResourceManager.GetString("errorTextoEnvioCodigoVerificacionDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible enviar el código de verificación. Intente más tarde..
        /// </summary>
        public static string errorTextoEnvioCodigoVerificacionMasTarde {
            get {
                return ResourceManager.GetString("errorTextoEnvioCodigoVerificacionMasTarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al procesar la solicitud..
        /// </summary>
        public static string errorTextoErrorProcesarSolicitud {
            get {
                return ResourceManager.GetString("errorTextoErrorProcesarSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el usuario o correo registrado para recuperar la contraseña..
        /// </summary>
        public static string errorTextoIdentificadorRecuperacionRequerido {
            get {
                return ResourceManager.GetString("errorTextoIdentificadorRecuperacionRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El identificador de {0} no debe exceder {1} caracteres..
        /// </summary>
        public static string errorTextoIdentificadorRedSocialLongitud {
            get {
                return ResourceManager.GetString("errorTextoIdentificadorRedSocialLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El identificador de usuario es inválido..
        /// </summary>
        public static string errorTextoIdentificadorUsuarioInvalido {
            get {
                return ResourceManager.GetString("errorTextoIdentificadorUsuarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo identificar el avatar seleccionado. Intente nuevamente..
        /// </summary>
        public static string errorTextoIdentificarAvatar {
            get {
                return ResourceManager.GetString("errorTextoIdentificarAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo iniciar el proceso de cambio de contraseña. Intente nuevamente..
        /// </summary>
        public static string errorTextoIniciarCambioContrasena {
            get {
                return ResourceManager.GetString("errorTextoIniciarCambioContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo iniciar la recuperación de contraseña. Intente nuevamente..
        /// </summary>
        public static string errorTextoIniciarRecuperacion {
            get {
                return ResourceManager.GetString("errorTextoIniciarRecuperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe un jugador asociado al usuario especificado..
        /// </summary>
        public static string errorTextoJugadorNoExiste {
            get {
                return ResourceManager.GetString("errorTextoJugadorNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró la partida.
        /// </summary>
        public static string errorTextoNoEncuentraPartida {
            get {
                return ResourceManager.GetString("errorTextoNoEncuentraPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el nombre del jugador..
        /// </summary>
        public static string errorTextoNombreJugadorRequerido {
            get {
                return ResourceManager.GetString("errorTextoNombreJugadorRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es obligatorio y no debe exceder 50 caracteres..
        /// </summary>
        public static string errorTextoNombreObligatorioLongitud {
            get {
                return ResourceManager.GetString("errorTextoNombreObligatorioLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese un nombre de usuario..
        /// </summary>
        public static string errorTextoNombreUsuarioRequerido {
            get {
                return ResourceManager.GetString("errorTextoNombreUsuarioRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible obtener la información actualizada del perfil..
        /// </summary>
        public static string errorTextoPerfilActualizarInformacion {
            get {
                return ResourceManager.GetString("errorTextoPerfilActualizarInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al preparar la solicitud de cambio de contraseña..
        /// </summary>
        public static string errorTextoPrepararSolicitudCambioContrasena {
            get {
                return ResourceManager.GetString("errorTextoPrepararSolicitudCambioContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible preparar la solicitud de inicio de sesión..
        /// </summary>
        public static string errorTextoPrepararSolicitudInicioSesion {
            get {
                return ResourceManager.GetString("errorTextoPrepararSolicitudInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un problema al procesar la solicitud..
        /// </summary>
        public static string errorTextoProblemaProcesarSolicitud {
            get {
                return ResourceManager.GetString("errorTextoProblemaProcesarSolicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible procesar la solicitud de actualización..
        /// </summary>
        public static string errorTextoProcesarSolicitudActualizacion {
            get {
                return ResourceManager.GetString("errorTextoProcesarSolicitudActualizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible procesar la solicitud de avatares..
        /// </summary>
        public static string errorTextoProcesarSolicitudAvatares {
            get {
                return ResourceManager.GetString("errorTextoProcesarSolicitudAvatares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible procesar la solicitud de cambio de contraseña..
        /// </summary>
        public static string errorTextoProcesarSolicitudCambioContrasena {
            get {
                return ResourceManager.GetString("errorTextoProcesarSolicitudCambioContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible procesar la solicitud de recuperación. Intente de nuevo..
        /// </summary>
        public static string errorTextoProcesarSolicitudRecuperacion {
            get {
                return ResourceManager.GetString("errorTextoProcesarSolicitudRecuperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible procesar la solicitud de reenvío. Intente nuevamente..
        /// </summary>
        public static string errorTextoProcesarSolicitudReenvio {
            get {
                return ResourceManager.GetString("errorTextoProcesarSolicitudReenvio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible procesar la solicitud de verificación..
        /// </summary>
        public static string errorTextoProcesarSolicitudVerificacion {
            get {
                return ResourceManager.GetString("errorTextoProcesarSolicitudVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo registrar la cuenta. Intente más tarde..
        /// </summary>
        public static string errorTextoRegistrarCuentaMasTarde {
            get {
                return ResourceManager.GetString("errorTextoRegistrarCuentaMasTarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un avatar válido antes de guardar los cambios..
        /// </summary>
        public static string errorTextoSeleccionAvatarValido {
            get {
                return ResourceManager.GetString("errorTextoSeleccionAvatarValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor reportó un error al actualizar la contraseña..
        /// </summary>
        public static string errorTextoServidorActualizarContrasena {
            get {
                return ResourceManager.GetString("errorTextoServidorActualizarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor reportó un error al actualizar el perfil..
        /// </summary>
        public static string errorTextoServidorActualizarPerfil {
            get {
                return ResourceManager.GetString("errorTextoServidorActualizarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo contactar al servidor para actualizar el catálogo de avatares..
        /// </summary>
        public static string errorTextoServidorCatalogoAvatares {
            get {
                return ResourceManager.GetString("errorTextoServidorCatalogoAvatares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo obtener el catálogo de avatares desde el servidor..
        /// </summary>
        public static string errorTextoServidorCatalogoAvataresDetalle {
            get {
                return ResourceManager.GetString("errorTextoServidorCatalogoAvataresDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor reportó un error al solicitar el código de verificación..
        /// </summary>
        public static string errorTextoServidorCodigoVerificacion {
            get {
                return ResourceManager.GetString("errorTextoServidorCodigoVerificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo obtener la información del avatar seleccionado..
        /// </summary>
        public static string errorTextoServidorInformacionAvatar {
            get {
                return ResourceManager.GetString("errorTextoServidorInformacionAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor reportó un error al iniciar la recuperación de contraseña..
        /// </summary>
        public static string errorTextoServidorInicioRecuperacion {
            get {
                return ResourceManager.GetString("errorTextoServidorInicioRecuperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor reportó un error al iniciar sesión..
        /// </summary>
        public static string errorTextoServidorInicioSesion {
            get {
                return ResourceManager.GetString("errorTextoServidorInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo contactar al servidor. Intente más tarde..
        /// </summary>
        public static string errorTextoServidorNoDisponible {
            get {
                return ResourceManager.GetString("errorTextoServidorNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor no respondió a tiempo. Intente nuevamente..
        /// </summary>
        public static string errorTextoServidorNoRespondioTiempo {
            get {
                return ResourceManager.GetString("errorTextoServidorNoRespondioTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor reportó un error al obtener la información del perfil..
        /// </summary>
        public static string errorTextoServidorObtenerPerfil {
            get {
                return ResourceManager.GetString("errorTextoServidorObtenerPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor reportó un error al reenviar el código..
        /// </summary>
        public static string errorTextoServidorReenviarCodigo {
            get {
                return ResourceManager.GetString("errorTextoServidorReenviarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se obtuvo respuesta del servidor. Intente más tarde..
        /// </summary>
        public static string errorTextoServidorSinRespuesta {
            get {
                return ResourceManager.GetString("errorTextoServidorSinRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor reportó un error al solicitar el cambio de contraseña..
        /// </summary>
        public static string errorTextoServidorSolicitudCambioContrasena {
            get {
                return ResourceManager.GetString("errorTextoServidorSolicitudCambioContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor tardó demasiado en responder. Intente más tarde..
        /// </summary>
        public static string errorTextoServidorTiempoAgotado {
            get {
                return ResourceManager.GetString("errorTextoServidorTiempoAgotado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor tardó demasiado en responder al solicitar los avatares..
        /// </summary>
        public static string errorTextoServidorTiempoAvatares {
            get {
                return ResourceManager.GetString("errorTextoServidorTiempoAvatares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor tardó demasiado en responder al validar el avatar..
        /// </summary>
        public static string errorTextoServidorTiempoValidarAvatar {
            get {
                return ResourceManager.GetString("errorTextoServidorTiempoValidarAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo contactar al servidor para validar el avatar seleccionado..
        /// </summary>
        public static string errorTextoServidorValidarAvatar {
            get {
                return ResourceManager.GetString("errorTextoServidorValidarAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor reportó un error al validar el código..
        /// </summary>
        public static string errorTextoServidorValidarCodigo {
            get {
                return ResourceManager.GetString("errorTextoServidorValidarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay una sesión activa. Inicie sesión nuevamente..
        /// </summary>
        public static string errorTextoSesionInactiva {
            get {
                return ResourceManager.GetString("errorTextoSesionInactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay una sesión activa para actualizar..
        /// </summary>
        public static string errorTextoSesionInactivaActualizar {
            get {
                return ResourceManager.GetString("errorTextoSesionInactivaActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay una sesión activa para cambiar la contraseña..
        /// </summary>
        public static string errorTextoSesionInactivaCambioContrasena {
            get {
                return ResourceManager.GetString("errorTextoSesionInactivaCambioContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo solicitar un nuevo código. Intente nuevamente..
        /// </summary>
        public static string errorTextoSolicitarNuevoCodigo {
            get {
                return ResourceManager.GetString("errorTextoSolicitarNuevoCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud de actualización es obligatoria..
        /// </summary>
        public static string errorTextoSolicitudActualizacionObligatoria {
            get {
                return ResourceManager.GetString("errorTextoSolicitudActualizacionObligatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró una solicitud de recuperación activa..
        /// </summary>
        public static string errorTextoSolicitudRecuperacionActiva {
            get {
                return ResourceManager.GetString("errorTextoSolicitudRecuperacionActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud de recuperación no es válida..
        /// </summary>
        public static string errorTextoSolicitudRecuperacionInvalida {
            get {
                return ResourceManager.GetString("errorTextoSolicitudRecuperacionInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay una solicitud de recuperación vigente..
        /// </summary>
        public static string errorTextoSolicitudRecuperacionVigente {
            get {
                return ResourceManager.GetString("errorTextoSolicitudRecuperacionVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró una solicitud de verificación activa..
        /// </summary>
        public static string errorTextoSolicitudVerificacionActiva {
            get {
                return ResourceManager.GetString("errorTextoSolicitudVerificacionActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud de verificación no es válida. Intente nuevamente..
        /// </summary>
        public static string errorTextoSolicitudVerificacionInvalida {
            get {
                return ResourceManager.GetString("errorTextoSolicitudVerificacionInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay una solicitud de verificación vigente..
        /// </summary>
        public static string errorTextoSolicitudVerificacionVigente {
            get {
                return ResourceManager.GetString("errorTextoSolicitudVerificacionVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe esperar {0} segundos para solicitar un nuevo código..
        /// </summary>
        public static string errorTextoTiempoEsperaCodigo {
            get {
                return ResourceManager.GetString("errorTextoTiempoEsperaCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El token de recuperación es obligatorio..
        /// </summary>
        public static string errorTextoTokenRecuperacionObligatorio {
            get {
                return ResourceManager.GetString("errorTextoTokenRecuperacionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El token de verificación es obligatorio..
        /// </summary>
        public static string errorTextoTokenVerificacionObligatorio {
            get {
                return ResourceManager.GetString("errorTextoTokenVerificacionObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario en uso.
        /// </summary>
        public static string errorTextoUsuarioEnUso {
            get {
                return ResourceManager.GetString("errorTextoUsuarioEnUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el usuario especificado..
        /// </summary>
        public static string errorTextoUsuarioNoEncontrado {
            get {
                return ResourceManager.GetString("errorTextoUsuarioNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La validación del código no está disponible en este momento..
        /// </summary>
        public static string errorTextoValidacionCodigoNoDisponible {
            get {
                return ResourceManager.GetString("errorTextoValidacionCodigoNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo verificar el código. Intente nuevamente..
        /// </summary>
        public static string errorTextoVerificarCodigo {
            get {
                return ResourceManager.GetString("errorTextoVerificarCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de querer expulsar a ?.
        /// </summary>
        public static string expulsarTextoConfirmacion {
            get {
                return ResourceManager.GetString("expulsarTextoConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXPULSAR.
        /// </summary>
        public static string expulsarTextoExpulsar {
            get {
                return ResourceManager.GetString("expulsarTextoExpulsar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXPULSAR JUGADOR.
        /// </summary>
        public static string expulsarTextoExpulsarJugador {
            get {
                return ResourceManager.GetString("expulsarTextoExpulsarJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añade la razón de la expulsión….
        /// </summary>
        public static string expulsarTextoRazonExpulsion {
            get {
                return ResourceManager.GetString("expulsarTextoRazonExpulsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ACEPTAR.
        /// </summary>
        public static string globalTextoAceptar {
            get {
                return ResourceManager.GetString("globalTextoAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AJUSTES.
        /// </summary>
        public static string globalTextoAjustes {
            get {
                return ResourceManager.GetString("globalTextoAjustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        public static string globalTextoApellido {
            get {
                return ResourceManager.GetString("globalTextoApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BUSCAR UN AMIGO.
        /// </summary>
        public static string globalTextoBuscarAmigo {
            get {
                return ResourceManager.GetString("globalTextoBuscarAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CANCELAR.
        /// </summary>
        public static string globalTextoCancelar {
            get {
                return ResourceManager.GetString("globalTextoCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLASIFICACIÓN.
        /// </summary>
        public static string globalTextoClasificacion {
            get {
                return ResourceManager.GetString("globalTextoClasificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿CÓMO JUGAR?.
        /// </summary>
        public static string globalTextoComoJugar {
            get {
                return ResourceManager.GetString("globalTextoComoJugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONFIRMAR.
        /// </summary>
        public static string globalTextoConfirmar {
            get {
                return ResourceManager.GetString("globalTextoConfirmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string globalTextoContraseña {
            get {
                return ResourceManager.GetString("globalTextoContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string globalTextoCorreo {
            get {
                return ResourceManager.GetString("globalTextoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREAR CUENTA.
        /// </summary>
        public static string globalTextoCrearCuenta {
            get {
                return ResourceManager.GetString("globalTextoCrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efectos de sonido.
        /// </summary>
        public static string globalTextoEfectosSonido {
            get {
                return ResourceManager.GetString("globalTextoEfectosSonido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIMINAR.
        /// </summary>
        public static string globalTextoEliminar {
            get {
                return ResourceManager.GetString("globalTextoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener mínimo 8 caracteres y máximo 15, así como contener mínimo una mayúscula, un número y un carácter especial.
        /// </summary>
        public static string globalTextoEspecificaContraseña {
            get {
                return ResourceManager.GetString("globalTextoEspecificaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el código de la partida:.
        /// </summary>
        public static string globalTextoIngreseCodigoPartida {
            get {
                return ResourceManager.GetString("globalTextoIngreseCodigoPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INVITACIONES.
        /// </summary>
        public static string globalTextoInvitaciones {
            get {
                return ResourceManager.GetString("globalTextoInvitaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INVITAR.
        /// </summary>
        public static string globalTextoInvitar {
            get {
                return ResourceManager.GetString("globalTextoInvitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string globalTextoNombre {
            get {
                return ResourceManager.GetString("globalTextoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REGRESAR.
        /// </summary>
        public static string globalTextoRegresar {
            get {
                return ResourceManager.GetString("globalTextoRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar un avatar.
        /// </summary>
        public static string globalTextoSeleccionarAvatar {
            get {
                return ResourceManager.GetString("globalTextoSeleccionarAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOLICITUDES.
        /// </summary>
        public static string globalTextoSolicitudes {
            get {
                return ResourceManager.GetString("globalTextoSolicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡UNIRSE!.
        /// </summary>
        public static string globalTextoUnirse {
            get {
                return ResourceManager.GetString("globalTextoUnirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UNIRSE A UNA SALA.
        /// </summary>
        public static string globalTextoUnirseASala {
            get {
                return ResourceManager.GetString("globalTextoUnirseASala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string globalTextoUsuario {
            get {
                return ResourceManager.GetString("globalTextoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen de las canciones.
        /// </summary>
        public static string globalTextoVolumenCanciones {
            get {
                return ResourceManager.GetString("globalTextoVolumenCanciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string idiomaTextoEspañol {
            get {
                return ResourceManager.GetString("idiomaTextoEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string idiomaTextoIdioma {
            get {
                return ResourceManager.GetString("idiomaTextoIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string idiomaTextoIngles {
            get {
                return ResourceManager.GetString("idiomaTextoIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico / Usuario.
        /// </summary>
        public static string inicioSesionTextoCorreoUsuario {
            get {
                return ResourceManager.GetString("inicioSesionTextoCorreoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENTRAR.
        /// </summary>
        public static string inicioSesionTextoEntrar {
            get {
                return ResourceManager.GetString("inicioSesionTextoEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENTRAR COMO INVITADO.
        /// </summary>
        public static string inicioSesionTextoEntrarInvitado {
            get {
                return ResourceManager.GetString("inicioSesionTextoEntrarInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string inicioSesionTextoOlvidasteContraseña {
            get {
                return ResourceManager.GetString("inicioSesionTextoOlvidasteContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  te invitó a unirse a su partida!.
        /// </summary>
        public static string invitacionTextoInvitado {
            get {
                return ResourceManager.GetString("invitacionTextoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INVITADO.
        /// </summary>
        public static string invitarAmigosTextoInvitado {
            get {
                return ResourceManager.GetString("invitarAmigosTextoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INVITAR AMIGOS.
        /// </summary>
        public static string invitarAmigosTextoInvitarAmigos {
            get {
                return ResourceManager.GetString("invitarAmigosTextoInvitarAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡INICIAR PARTIDA!.
        /// </summary>
        public static string partidaAdminTextoIniciarPartida {
            get {
                return ResourceManager.GetString("partidaAdminTextoIniciarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INVITAR AL CORREO.
        /// </summary>
        public static string partidaAdminTextoInvitarCorreo {
            get {
                return ResourceManager.GetString("partidaAdminTextoInvitarCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string partidaTextoChat {
            get {
                return ResourceManager.GetString("partidaTextoChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código:.
        /// </summary>
        public static string partidaTextoCodigo {
            get {
                return ResourceManager.GetString("partidaTextoCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida en curso.
        /// </summary>
        public static string partidaTextoPartidaEnCurso {
            get {
                return ResourceManager.GetString("partidaTextoPartidaEnCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ronda:.
        /// </summary>
        public static string partidaTextoRonda {
            get {
                return ResourceManager.GetString("partidaTextoRonda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CAMBIAR CONTRASEÑA.
        /// </summary>
        public static string perfilTextoCambiarContraseña {
            get {
                return ResourceManager.GetString("perfilTextoCambiarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR CAMBIOS.
        /// </summary>
        public static string perfilTextoGuardarCambios {
            get {
                return ResourceManager.GetString("perfilTextoGuardarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MI PERFIL.
        /// </summary>
        public static string perfilTextoMiPerfil {
            get {
                return ResourceManager.GetString("perfilTextoMiPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega alguna red social:.
        /// </summary>
        public static string perfilTextoRedesSociales {
            get {
                return ResourceManager.GetString("perfilTextoRedesSociales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AMIGOS.
        /// </summary>
        public static string principalTextoAmigos {
            get {
                return ResourceManager.GetString("principalTextoAmigos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREAR UNA SALA.
        /// </summary>
        public static string principalTextoCrearSala {
            get {
                return ResourceManager.GetString("principalTextoCrearSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Difícil.
        /// </summary>
        public static string principalTextoDificil {
            get {
                return ResourceManager.GetString("principalTextoDificil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dificultad:.
        /// </summary>
        public static string principalTextoDificultad {
            get {
                return ResourceManager.GetString("principalTextoDificultad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fácil.
        /// </summary>
        public static string principalTextoFacil {
            get {
                return ResourceManager.GetString("principalTextoFacil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma de las canciones.
        /// </summary>
        public static string principalTextoIdiomaCanciones {
            get {
                return ResourceManager.GetString("principalTextoIdiomaCanciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡JUGAR!.
        /// </summary>
        public static string principalTextoJugar {
            get {
                return ResourceManager.GetString("principalTextoJugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Media.
        /// </summary>
        public static string principalTextoMedia {
            get {
                return ResourceManager.GetString("principalTextoMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mixto.
        /// </summary>
        public static string principalTextoMixto {
            get {
                return ResourceManager.GetString("principalTextoMixto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de rondas:.
        /// </summary>
        public static string principalTextoNumeroRondas {
            get {
                return ResourceManager.GetString("principalTextoNumeroRondas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de la ronda (segundos).
        /// </summary>
        public static string principalTextoTiempoRonda {
            get {
                return ResourceManager.GetString("principalTextoTiempoRonda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventana Principal.
        /// </summary>
        public static string principalTextoTitulo {
            get {
                return ResourceManager.GetString("principalTextoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de querer salir de la partida?.
        /// </summary>
        public static string salirPartidaTextoConfirmación {
            get {
                return ResourceManager.GetString("salirPartidaTextoConfirmación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en-MX.
        /// </summary>
        public static string TagEspañol {
            get {
                return ResourceManager.GetString("TagEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en-US.
        /// </summary>
        public static string TagIngles {
            get {
                return ResourceManager.GetString("TagIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Sesión.
        /// </summary>
        public static string tituloTextoInicioSesion {
            get {
                return ResourceManager.GetString("tituloTextoInicioSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MUSICAL.
        /// </summary>
        public static string tituloTextoMusical {
            get {
                return ResourceManager.GetString("tituloTextoMusical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PICTIONARY.
        /// </summary>
        public static string tituloTextoPictionary {
            get {
                return ResourceManager.GetString("tituloTextoPictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cuenta.
        /// </summary>
        public static string tituloTextoRegistroUsuarios {
            get {
                return ResourceManager.GetString("tituloTextoRegistroUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala.
        /// </summary>
        public static string tituloTextoVentanaPrincipal {
            get {
                return ResourceManager.GetString("tituloTextoVentanaPrincipal", resourceCulture);
            }
        }
    }
}
