//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioAvatares {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvatarDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class AvatarDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaRelativaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaRelativa {
            get {
                return this.RutaRelativaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaRelativaField, value) != true)) {
                    this.RutaRelativaField = value;
                    this.RaisePropertyChanged("RutaRelativa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioAvatares.ICatalogoAvatares")]
    public interface ICatalogoAvatares {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoAvatares/ObtenerAvataresDisponibles", ReplyAction="http://tempuri.org/ICatalogoAvatares/ObtenerAvataresDisponiblesResponse")]
        PictionaryMusicalCliente.PictionaryServidorServicioAvatares.AvatarDTO[] ObtenerAvataresDisponibles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICatalogoAvatares/ObtenerAvataresDisponibles", ReplyAction="http://tempuri.org/ICatalogoAvatares/ObtenerAvataresDisponiblesResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioAvatares.AvatarDTO[]> ObtenerAvataresDisponiblesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICatalogoAvataresChannel : PictionaryMusicalCliente.PictionaryServidorServicioAvatares.ICatalogoAvatares, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogoAvataresClient : System.ServiceModel.ClientBase<PictionaryMusicalCliente.PictionaryServidorServicioAvatares.ICatalogoAvatares>, PictionaryMusicalCliente.PictionaryServidorServicioAvatares.ICatalogoAvatares {
        
        public CatalogoAvataresClient() {
        }
        
        public CatalogoAvataresClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogoAvataresClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoAvataresClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogoAvataresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PictionaryMusicalCliente.PictionaryServidorServicioAvatares.AvatarDTO[] ObtenerAvataresDisponibles() {
            return base.Channel.ObtenerAvataresDisponibles();
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioAvatares.AvatarDTO[]> ObtenerAvataresDisponiblesAsync() {
            return base.Channel.ObtenerAvataresDisponiblesAsync();
        }
    }
}
