//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancion
    {
        public int idCancion { get; set; }
        public string Nombre { get; set; }
        public string Cancion_Ruta { get; set; }
        public string Idioma { get; set; }
        public int Artista_idArtista { get; set; }
        public int Genero_idGenero { get; set; }
    
        public virtual Artista Artista { get; set; }
        public virtual Genero Genero { get; set; }
    }
}
