//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedSocial
    {
        public int idRedSocial { get; set; }
        public int Jugador_idJugador { get; set; }
        public string Instagram { get; set; }
        public string discord { get; set; }
        public string facebook { get; set; }
        public string x { get; set; }
    
        public virtual Jugador Jugador { get; set; }
    }
}
