//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudRecuperarCuentaDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class SolicitudRecuperarCuentaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoSolicitudRecuperacionDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class ResultadoSolicitudRecuperacionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CodigoEnviadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CuentaEncontradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenCodigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CodigoEnviado {
            get {
                return this.CodigoEnviadoField;
            }
            set {
                if ((this.CodigoEnviadoField.Equals(value) != true)) {
                    this.CodigoEnviadoField = value;
                    this.RaisePropertyChanged("CodigoEnviado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoDestino {
            get {
                return this.CorreoDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoDestinoField, value) != true)) {
                    this.CorreoDestinoField = value;
                    this.RaisePropertyChanged("CorreoDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CuentaEncontrada {
            get {
                return this.CuentaEncontradaField;
            }
            set {
                if ((this.CuentaEncontradaField.Equals(value) != true)) {
                    this.CuentaEncontradaField = value;
                    this.RaisePropertyChanged("CuentaEncontrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenCodigo {
            get {
                return this.TokenCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenCodigoField, value) != true)) {
                    this.TokenCodigoField = value;
                    this.RaisePropertyChanged("TokenCodigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReenviarCodigoDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class ReenviarCodigoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenCodigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenCodigo {
            get {
                return this.TokenCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenCodigoField, value) != true)) {
                    this.TokenCodigoField = value;
                    this.RaisePropertyChanged("TokenCodigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoSolicitudCodigoDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class ResultadoSolicitudCodigoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CodigoEnviadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorreoYaRegistradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UsuarioYaRegistradoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CodigoEnviado {
            get {
                return this.CodigoEnviadoField;
            }
            set {
                if ((this.CodigoEnviadoField.Equals(value) != true)) {
                    this.CodigoEnviadoField = value;
                    this.RaisePropertyChanged("CodigoEnviado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CorreoYaRegistrado {
            get {
                return this.CorreoYaRegistradoField;
            }
            set {
                if ((this.CorreoYaRegistradoField.Equals(value) != true)) {
                    this.CorreoYaRegistradoField = value;
                    this.RaisePropertyChanged("CorreoYaRegistrado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenCodigo {
            get {
                return this.TokenCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenCodigoField, value) != true)) {
                    this.TokenCodigoField = value;
                    this.RaisePropertyChanged("TokenCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UsuarioYaRegistrado {
            get {
                return this.UsuarioYaRegistradoField;
            }
            set {
                if ((this.UsuarioYaRegistradoField.Equals(value) != true)) {
                    this.UsuarioYaRegistradoField = value;
                    this.RaisePropertyChanged("UsuarioYaRegistrado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmarCodigoDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class ConfirmarCodigoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoIngresadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenCodigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoIngresado {
            get {
                return this.CodigoIngresadoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoIngresadoField, value) != true)) {
                    this.CodigoIngresadoField = value;
                    this.RaisePropertyChanged("CodigoIngresado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenCodigo {
            get {
                return this.TokenCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenCodigoField, value) != true)) {
                    this.TokenCodigoField = value;
                    this.RaisePropertyChanged("TokenCodigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoOperacionDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class ResultadoOperacionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OperacionExitosaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OperacionExitosa {
            get {
                return this.OperacionExitosaField;
            }
            set {
                if ((this.OperacionExitosaField.Equals(value) != true)) {
                    this.OperacionExitosaField = value;
                    this.RaisePropertyChanged("OperacionExitosa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActualizarContrasenaDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class ActualizarContrasenaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NuevaContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenCodigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NuevaContrasena {
            get {
                return this.NuevaContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.NuevaContrasenaField, value) != true)) {
                    this.NuevaContrasenaField = value;
                    this.RaisePropertyChanged("NuevaContrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenCodigo {
            get {
                return this.TokenCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenCodigoField, value) != true)) {
                    this.TokenCodigoField = value;
                    this.RaisePropertyChanged("TokenCodigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioCambioContrasena.ICambiarContrasenaManejador")]
    public interface ICambiarContrasenaManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/SolicitarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/SolicitarCodigoRecuperacionRespons" +
            "e")]
        PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoSolicitudRecuperacionDTO SolicitarCodigoRecuperacion(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.SolicitudRecuperarCuentaDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/SolicitarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/SolicitarCodigoRecuperacionRespons" +
            "e")]
        System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoSolicitudRecuperacionDTO> SolicitarCodigoRecuperacionAsync(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.SolicitudRecuperarCuentaDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/ReenviarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/ReenviarCodigoRecuperacionResponse" +
            "")]
        PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoSolicitudCodigoDTO ReenviarCodigoRecuperacion(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ReenviarCodigoDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/ReenviarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/ReenviarCodigoRecuperacionResponse" +
            "")]
        System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoSolicitudCodigoDTO> ReenviarCodigoRecuperacionAsync(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ReenviarCodigoDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/ConfirmarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/ConfirmarCodigoRecuperacionRespons" +
            "e")]
        PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoOperacionDTO ConfirmarCodigoRecuperacion(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ConfirmarCodigoDTO confirmacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/ConfirmarCodigoRecuperacion", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/ConfirmarCodigoRecuperacionRespons" +
            "e")]
        System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoOperacionDTO> ConfirmarCodigoRecuperacionAsync(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ConfirmarCodigoDTO confirmacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/ActualizarContrasena", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/ActualizarContrasenaResponse")]
        PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoOperacionDTO ActualizarContrasena(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ActualizarContrasenaDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICambiarContrasenaManejador/ActualizarContrasena", ReplyAction="http://tempuri.org/ICambiarContrasenaManejador/ActualizarContrasenaResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoOperacionDTO> ActualizarContrasenaAsync(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ActualizarContrasenaDTO solicitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICambiarContrasenaManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ICambiarContrasenaManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CambiarContrasenaManejadorClient : System.ServiceModel.ClientBase<PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ICambiarContrasenaManejador>, PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ICambiarContrasenaManejador {
        
        public CambiarContrasenaManejadorClient() {
        }
        
        public CambiarContrasenaManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CambiarContrasenaManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CambiarContrasenaManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CambiarContrasenaManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoSolicitudRecuperacionDTO SolicitarCodigoRecuperacion(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.SolicitudRecuperarCuentaDTO solicitud) {
            return base.Channel.SolicitarCodigoRecuperacion(solicitud);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoSolicitudRecuperacionDTO> SolicitarCodigoRecuperacionAsync(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.SolicitudRecuperarCuentaDTO solicitud) {
            return base.Channel.SolicitarCodigoRecuperacionAsync(solicitud);
        }
        
        public PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoSolicitudCodigoDTO ReenviarCodigoRecuperacion(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ReenviarCodigoDTO solicitud) {
            return base.Channel.ReenviarCodigoRecuperacion(solicitud);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoSolicitudCodigoDTO> ReenviarCodigoRecuperacionAsync(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ReenviarCodigoDTO solicitud) {
            return base.Channel.ReenviarCodigoRecuperacionAsync(solicitud);
        }
        
        public PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoOperacionDTO ConfirmarCodigoRecuperacion(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ConfirmarCodigoDTO confirmacion) {
            return base.Channel.ConfirmarCodigoRecuperacion(confirmacion);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoOperacionDTO> ConfirmarCodigoRecuperacionAsync(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ConfirmarCodigoDTO confirmacion) {
            return base.Channel.ConfirmarCodigoRecuperacionAsync(confirmacion);
        }
        
        public PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoOperacionDTO ActualizarContrasena(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ActualizarContrasenaDTO solicitud) {
            return base.Channel.ActualizarContrasena(solicitud);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ResultadoOperacionDTO> ActualizarContrasenaAsync(PictionaryMusicalCliente.PictionaryServidorServicioCambioContrasena.ActualizarContrasenaDTO solicitud) {
            return base.Channel.ActualizarContrasenaAsync(solicitud);
        }
    }
}
