//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReenviarCodigoDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class ReenviarCodigoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenCodigoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenCodigo {
            get {
                return this.TokenCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenCodigoField, value) != true)) {
                    this.TokenCodigoField = value;
                    this.RaisePropertyChanged("TokenCodigo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoSolicitudCodigoDTO", Namespace="http://schemas.datacontract.org/2004/07/Servicios.Contratos.DTOs")]
    [System.SerializableAttribute()]
    public partial class ResultadoSolicitudCodigoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CodigoEnviadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorreoYaRegistradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenCodigoField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UsuarioYaRegistradoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CodigoEnviado {
            get {
                return this.CodigoEnviadoField;
            }
            set {
                if ((this.CodigoEnviadoField.Equals(value) != true)) {
                    this.CodigoEnviadoField = value;
                    this.RaisePropertyChanged("CodigoEnviado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CorreoYaRegistrado {
            get {
                return this.CorreoYaRegistradoField;
            }
            set {
                if ((this.CorreoYaRegistradoField.Equals(value) != true)) {
                    this.CorreoYaRegistradoField = value;
                    this.RaisePropertyChanged("CorreoYaRegistrado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenCodigo {
            get {
                return this.TokenCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenCodigoField, value) != true)) {
                    this.TokenCodigoField = value;
                    this.RaisePropertyChanged("TokenCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UsuarioYaRegistrado {
            get {
                return this.UsuarioYaRegistradoField;
            }
            set {
                if ((this.UsuarioYaRegistradoField.Equals(value) != true)) {
                    this.UsuarioYaRegistradoField = value;
                    this.RaisePropertyChanged("UsuarioYaRegistrado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PictionaryServidorServicioReenvioCodigoVerificacion.IReenviarCodigoVerificacionMa" +
        "nejador")]
    public interface IReenviarCodigoVerificacionManejador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReenviarCodigoVerificacionManejador/ReenviarCodigoVerificacio" +
            "n", ReplyAction="http://tempuri.org/IReenviarCodigoVerificacionManejador/ReenviarCodigoVerificacio" +
            "nResponse")]
        PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ResultadoSolicitudCodigoDTO ReenviarCodigoVerificacion(PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ReenviarCodigoDTO solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReenviarCodigoVerificacionManejador/ReenviarCodigoVerificacio" +
            "n", ReplyAction="http://tempuri.org/IReenviarCodigoVerificacionManejador/ReenviarCodigoVerificacio" +
            "nResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ResultadoSolicitudCodigoDTO> ReenviarCodigoVerificacionAsync(PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ReenviarCodigoDTO solicitud);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReenviarCodigoVerificacionManejador/ReenviarCodigoRecuperacion", ReplyAction="http://tempuri.org/IReenviarCodigoVerificacionManejador/ReenviarCodigoRecuperacionResponse")]
        PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ResultadoSolicitudCodigoDTO ReenviarCodigoRecuperacion(PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ReenviarCodigoDTO solicitud);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReenviarCodigoVerificacionManejador/ReenviarCodigoRecuperacion", ReplyAction="http://tempuri.org/IReenviarCodigoVerificacionManejador/ReenviarCodigoRecuperacionResponse")]
        System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ResultadoSolicitudCodigoDTO> ReenviarCodigoRecuperacionAsync(PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ReenviarCodigoDTO solicitud);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReenviarCodigoVerificacionManejadorChannel : PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.IReenviarCodigoVerificacionManejador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReenviarCodigoVerificacionManejadorClient : System.ServiceModel.ClientBase<PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.IReenviarCodigoVerificacionManejador>, PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.IReenviarCodigoVerificacionManejador {
        
        public ReenviarCodigoVerificacionManejadorClient() {
        }
        
        public ReenviarCodigoVerificacionManejadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReenviarCodigoVerificacionManejadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReenviarCodigoVerificacionManejadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReenviarCodigoVerificacionManejadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ResultadoSolicitudCodigoDTO ReenviarCodigoVerificacion(PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ReenviarCodigoDTO solicitud) {
            return base.Channel.ReenviarCodigoVerificacion(solicitud);
        }
        
        public System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ResultadoSolicitudCodigoDTO> ReenviarCodigoVerificacionAsync(PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ReenviarCodigoDTO solicitud) {
            return base.Channel.ReenviarCodigoVerificacionAsync(solicitud);
        }

        public PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ResultadoSolicitudCodigoDTO ReenviarCodigoRecuperacion(PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ReenviarCodigoDTO solicitud) {
            return base.Channel.ReenviarCodigoRecuperacion(solicitud);
        }

        public System.Threading.Tasks.Task<PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ResultadoSolicitudCodigoDTO> ReenviarCodigoRecuperacionAsync(PictionaryMusicalCliente.PictionaryServidorServicioReenvioCodigoVerificacion.ReenviarCodigoDTO solicitud) {
            return base.Channel.ReenviarCodigoRecuperacionAsync(solicitud);
        }
    }
}
